# User config
author: "Peng Manshu  ( ´◔︎ ‸◔︎`) ~"
tagline: "Pineapple Certfied Jekyll Theme"
description: "PMS is a cute pig testing her github.io..."
keywords: "Pineapple, Pineapple Pizza, Pineapple House"
email: "manshu.peng@outlook.com"
linkedin: "https://www.linkedin.com/"
twitter: "https://twitter.com/"
github: "https://github.com/"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed