# User config
author: "Li Yuchen  ╮(๑•́ ₃•̀๑)╭"
tagline: "Pineapple Certfied Jekyll Theme"
description: "LYC is testing his github.io..."
# keywords: "Pineapple, Pineapple Pizza, Pineapple House"
email: "yuchener.li@outlook.com"
linkedin: "https://www.linkedin.com/"
twitter: "https://twitter.com/"
github: "https://github.com/"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed